# Generated by Django 3.1.5 on 2024-09-02 05:58

import detection.models
from django.db import migrations, models
import webdev.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadalert',
            name='image',
            field=models.ImageField(storage=webdev.storage_backends.PublicMediaStorage(), upload_to=detection.models.scrambleUploadedFilename, verbose_name='Uploaded image'),
        ),
    ]
